# Site settings
title: Marc Friedli 
description: Marc Friedli |   Überblick
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Marc Friedli
user_description: Persönliche Website von Marc Friedli, mit Informationen zu ihm, seinem Werdegang und seinen Projekten.
user_title: 
email: moin@marcfriedli.ch
linkedin_username: https://www.linkedin.com/in/marc-friedli-758775228/
github_username:  MaFr5102
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
